### ISSUE TITLE
Fails to compile properly

### ISSUE THREAD

**Issue by rdebath** [dim13/golyb#1]
I've tried your installation command in the usual places; in a bare directory or in a cloned copy of your repository. I've also tried the obvious setting of a 'GOPATH' environment variable (an absolute path pointing at the current directory).

I don't imagine it's your fault in any way, you're just following a dumb edict from someone that this is the `one true way` to do things. The error message I'm getting do seem to imply something JAVAesq.

....... a bit later ... 

Okay, this stupid hack seems to compile an executable with the default `main` name. I assume it's not how I'm supposed to do it, and it does seem a bit slow so I guess I've omitted some optimisation flags too.

Any suggestions please?

```
$ ln -s . src
$ ln -s . github.com
$ ln -s . dim13
$ ln -s . golyb
$ GOPATH=`pwd` go build cmd/golyb/main.go
$ time ./main -file testdata/mandelbrot.b | md5sum
5024283fa65866ddd347b877798e84d8  -

real    0m26.104s
user    0m26.076s
sys     0m0.052s
$ time ./deadbeef testdata/mandelbrot.b | md5sum
5024283fa65866ddd347b877798e84d8  -

real    0m6.973s
user    0m6.964s
sys     0m0.028s
$
```

**Comment by dim13** [comment]
`go get` is the official way to install Go programs. Please read https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies first.

Upon execution of `go get github.com/dim13/golyb/cmd/golyb` the source code will appear in `~/go/src/github.com/dim13/golyb/` and the binary in `~/go/bin/golyb`. Beginning with Go1.8 you can omit setting of `$GOPATH` manually. No further hackery is required. 

Regarding speed, the aim of this project was never to be THE fastest interpreter, but rather a playground on AST optimisations with moderate speed gain, as achieved. You can turn all optimisations off with `-noop` flag (per default all optimisations will be applied).

Dumping of modified and not modified AST is provided with `-dump` flag.

**Comment by rdebath** [comment]
Go 1.8, okay it seems `go` still has significant changes happening quickly; I'll have to have another look.

Looks like I didn't try the combination of <code>GOPATH=&#96;pwd&#96; go get ...</code> on the v1.3 in Debian stable. (sigh!) 

Okay, back to the speed, I realise you're not (yet?) going for top speeds as you'd be forced to do some sort of code generation for that and I'd be comparing against significantly faster translators and compilers.

The [deadbeef](https://github.com/rdebath/Brainfuck/blob/master/extras/deadbeef.c) interpreter is a small plain C89 interpreter with just minimal one and two instruction lookahead optimisations. Your optimisations are such that you should be clobbering it. Instead you're running something like a third of the speed. I was guessing that this was my problem with the `go` compiler but perhaps not.

Looking more closely at your code I think the issue is that your `Execute` for/switch loop has an array of function pointers for each of tape allocation scheme. If you change this so there's a separate execute loop for each scheme (and the compiler manages to inline all those tiny functions) you should be able to get that three or four times speed improvement quite simply on the static tape method. The dynamic tape would also be a lot quicker.

**Comment by dim13** [comment]
On debian systems I would recommend you to use https://github.com/niemeyer/godeb for fresh go versions. In-repo version is outdated as hell (Go1.3 was released 2014).

Sure, I could embed everything by storage type, but this was not the point of exercise, and everything else as go-ish. ;)

Some time improvements could be achieved with stdout caching (up to 10..20% of runtime), but again I aimed other things.

**Comment by dim13** [comment]
@rdebath I optimised `execute.go` (unnecessary copy of local variable in loop), so now my implementation is quite comparable with yours:

```
$ time ./golyb -file testdata/mandelbrot.b -out /dev/null
       11.36 real        11.30 user         0.03 sys

$ time ./deadbeef < testdata/mandelbrot.b > /dev/null
       11.42 real        11.40 user         0.01 sys
```
(best time of three runs, executed on 1.3 GHz Intel Core i5)

**Comment by rdebath** [comment]
Okay, I've pushed it into my [speed testing](https://rawgit.com/rdebath/Brainfuck/results/index.html), you should hide the compiled ones as they have a completely unfair advantage.

Firstly, I suggest you use `fmt.Print(string(t.cell[t.pos+off]))` to print the cells, it gives a reasonable result for >127 without erroring.

The `Long` and `Prime` tests are good, but there are still more optimisations available. 
The `Counter` test really does't optimise so it basically runs at the raw instruction rate of the interpreter. This seems to be saying your raw rate takes about 3.3 times longer than `deadbeef` on an i7 (a bit better on an i5).

This doesn't match with your results, okay first the simple question ... did you tell `gcc` to optimise `deadbeef`?

```
$ gcc -O2 -o deadbeef deadbeef.c
$ time ./deadbeef mandelbrot.b | md5sum
5024283fa65866ddd347b877798e84d8  -

real    0m5.645s
user    0m5.636s
sys     0m0.048s
$ time ./golyb -file mandelbrot.b | md5sum
5024283fa65866ddd347b877798e84d8  -

real    0m10.266s
user    0m10.264s
sys     0m0.092s
$
```

Oh BTW I'm still not liking go... The language itself seems okay, but. Errors are for code that can't be compiled. Warnings are for code that might not work as you like. They are still ASSuming that their politics are perfect and they are refusing to let their compiler warn about unusual constructs that might cause problems if used oddly. Anyone who's been in support knows the sort, you tell the l-user to do something but they don't bother because they know it'll fail. Then you have to go through all sorts of horse shit to get the arrogant idiot to Just Fucking Do It.

**Comment by dim13** [comment]
Indeed, it seems I forgot -02 option. Anyway, I'm pretty happy with results. Thanks for comparison chart!

PS: there are no warning, only errors -- and that's a right thing.
